task_name: mlee

bert_vocab: deep_event_mine/data/bert/scibert_scivocab_cased/vocab.txt
bert_model: deep_event_mine/data/bert/scibert_scivocab_cased
model_path: deep_event_mine/data/models/mlee/model/
saved_params: deep_event_mine/data/models/mlee/mlee.param

train_data: deep_event_mine/data/my-pubmed/processed-text/text/

ev_eval_script_path: deep_event_mine/eval/scripts/eval-ev-cg.py
a2_entities: ['DNA_domain_or_region', 'Protein_domain_or_region']
raw_text: True
ner_predict_all: True

result_dir: deep_event_mine/experiments/cg/predict-gold-dev/

freeze_bert: True
compute_dem_loss: False
compute_metrics: False
gpu: 0
batchsize: 32
seed: 42
