task_name: cg

bert_model: data/bert/scibert_scivocab_cased
model_path: data/models/cg/model/
saved_params: data/models/cg/cg.param

test_data: data/corpora/cg/play_around/

ev_eval_script_path: eval/scripts/eval-ev-cg.py
a2_entities: ['DNA_domain_or_region', 'Protein_domain_or_region']
raw_text: False
ner_predict_all: False

result_dir: experiments/cg/predict-gold-dev/

compute_metrics: False
gpu: 0
batchsize: 16
seed: 42
