task_name: cg

bert_model: data/bert/scibert_scivocab_cased
model_path: data/models/cg/model/
saved_params: data/models/cg/cg.param

train_data: data/corpora/cg/train/
eval_data: data/corpora/cg/dev/

ev_eval_script_path: eval/scripts/eval-ev-cg.py
a2_entities: ['DNA_domain_or_region', 'Protein_domain_or_region']
raw_text: True
ner_predict_all: True

result_dir: experiments/cg/predict-gold-dev/
refdir: data/original_corpora/cg/dev/
refdir_offset: data/corpora/cg/dev/
preddir: experiments/cg/predict-gold-dev/ev-last/ev-orig-a2/
preddir_offset: experiments/cg/predict-gold-dev/ev-last/ev-tok-a2/
outdir: experiments/cg/predict-gold-dev/ev-last/
weights_name: train_33_33_new
checkpoint_path: parameters/train_33_33_new_checkpoint.pt

train: True
resume: True
compute_metrics: False
rel_balance: True
freeze_bert: False
gpu: 0
batchsize: 16
seed: 42
ent_balance_mult: 2
rel_balance_mult: 2

