task_name: cg

bert_model: data/bert/scibert_scivocab_cased
model_path: data/models/cg/model/
saved_params: data/models/cg/cg.param

train_data: data/corpora/cg/train/

ev_eval_script_path: eval/scripts/eval-ev-cg.py
a2_entities: ['DNA_domain_or_region', 'Protein_domain_or_region']
raw_text: True
ner_predict_all: True

result_dir: experiments/cg/predict-gold-dev/
weights_name: train_50
checkpoint_path: parameters/train_50.pt

resume: True
gpu: 0
batchsize: 16
seed: 42
balance_mult: 1