task_name: mlee

bert_vocab: deep_event_mine/data/bert/scibert_scivocab_cased/vocab.txt
bert_model: deep_event_mine/data/bert/scibert_scivocab_cased
model_path: deep_event_mine/data/models/cg/model/
saved_params: deep_event_mine/data/models/cg/cg.param


a2_entities: ['DNA_domain_or_region', 'Protein_domain_or_region']
raw_text: True
ner_predict_all: True

result_dir: deep_event_mine/train/

compute_dem_loss: False
compute_metrics: False
gpu: 0
batchsize: 32
seed: 42
